AWSTemplateFormatVersion: 2010-09-09
Description: |
  EKS cluster (dedicated VPC: true, dedicated IAM: true) [created and managed by
  eksctl]  

### Parameters ### 

Parameters:
  VpcName:
    Description: Enter VPCName
    Type: String
    Default: ''
  VpcCidrBlock:
    Description: Enter CidrBlock 
    Type: String
    Default: ''
  SubnetId:
    Description: Enter SubnetID
    Type: String
    Default: ''
  SubnetCidrBlock:
    Description: Enter CidrBlock 
    Type: String
    Default: ''
  SubnetId:
    Description: Enter SubnetID
    Type: String
    Default: ''
  SubnetCidrBlock:
    Description: Enter CidrBlock 
    Type: String
    Default: ''
  AvailabilityZone:
    Description: Enter AZ
    Type: String
    Default: ''
  ControlPlaneName:
    Description: Enter name
    Type: String
    Default: ''

### mapping ####
Mappings:
  ServicePrincipalPartitionMap:
    aws:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
    aws-cn:
      EC2: ec2.amazonaws.com.cn
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
    aws-us-gov:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
### Resources ####    

Resources:

  ### Network Resources ###
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      Name: !Ref VpcName
      CidrBlock: ''
      EnableDnsSupport: true

  SubnetPublic1:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: ''
      CidrBlock: ''
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC

  SubnetPublic2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: ''
      CidrBlock: ''
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC

  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
  
  PublicSubnetRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
    
  
  RouteTableAssociationPublic1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetPublic1
  
  RouteTableAssociationPublic2:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetPublic2


  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: keyname
          Value: Internet
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  

  
  ControlPlane:
      Type: 'AWS::EKS::Cluster'
      Properties:
        Name: !Ref ControlPlaneName
        ResourcesVpcConfig:
          SecurityGroupIds:
            - !Ref ControlPlaneSecurityGroup
          SubnetIds:
            - !Ref SubnetPublic1
            - !Ref SubnetPublic2
        RoleArn: !GetAtt 
          - ServiceRole
          - Arn
        Version: '1.18'

  ClusterSharedNodeSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Communication between all nodes in the cluster
      VpcId: !Ref VPC
  
  ControlPlaneSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Communication between the control plane and worker nodegroups
        VpcId: !Ref VPC
  
  IngressNodeToDefaultClusterSG:
      Type: 'AWS::EC2::SecurityGroupIngress'
      Properties:
        Description: Allow unmanaged nodes to communicate with control plane (all ports)
        FromPort: 0
        GroupId: !GetAtt 
          - ControlPlane
          - ClusterSecurityGroupId
        IpProtocol: '-1'
        SourceSecurityGroupId: !Ref ClusterSharedNodeSecurityGroup
        ToPort: 65535
        
  ### IAM Resources ###

  ServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - !FindInMap
                  - ServicePrincipalPartitionMap
                  - !Ref "AWS::Partition"
                  - EKS
                - !FindInMap
                  - ServicePrincipalPartitionMap
                  - !Ref "AWS::Partition"
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSClusterPolicy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSVPCResourceController"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}/ServiceRole"
  

