AWSTemplateFormatVersion: 2010-09-09
Resources:

#### Eks NODE GROUP######
  
  nodegroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: ControlPlane-29HUXItVw54f
      NodeRole: !GetAtt EKSNodeRole.Arn
      NodegroupName: slave-node
      Subnets: 
        - subnet-0f7b479128a73aac8
        - subnet-08d910431385738d6

  EKSNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    
      
  SG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: >-
        Communication between the control plane and worker nodes
      SecurityGroupIngress:
        - Description: >-
            [IngressInterCluster] Allow worker nodes
            communicate with control plane (kubelet and workload TCP ports)
          FromPort: 1025
          IpProtocol: tcp
          SourceSecurityGroupId: sg-00e6e3f4a3d0c8a70
          ToPort: 65535
        - Description: >-
            [IngressInterClusterAPI] Allow worker nodes  to
            communicate with control plane (workloads using HTTPS port, commonly
            used with extension API servers)
          FromPort: 443
          IpProtocol: tcp
          SourceSecurityGroupId: sg-00e6e3f4a3d0c8a70
          ToPort: 443
      VpcId: vpc-07c1b1a3a2e670d69
