apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: front-end-rs
  labels:
    portion: reviews
    tier: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      name: front-end
      labels:
        portion: reviews
        tier: front-end
    spec:
      containers:
      - name: reviews-container
        image: nginx