  AWSTemplateFormatVersion: 2010-09-09
  Description: sec gr
  Resources:
   ## VPC
    myVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
  ## Private Subnet
    PUBSUBNET:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-1a
        VpcId: !Ref myVPC
        CidrBlock: 10.0.0.0/24

  ## Second Subnet
    PRSUBNET:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-1a
        VpcId: !Ref myVPC
        CidrBlock: 10.0.1.0/24

    CUSTOMRT:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref myVPC

    SourceSG:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        VpcId: !Ref myVPC
        GroupDescription: Sample source security group
    TargetSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: !Ref myVPC
        GroupDescription: Sample target security group
    OutboundRule:
      Type: AWS::EC2::SecurityGroupEgress
      Properties:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        DestinationSecurityGroupId:
          Fn::GetAtt:
          - TargetSG
          - GroupId
        GroupId:
          Fn::GetAtt:
          - SourceSG
          - GroupId
    InboundRule:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        SourceSecurityGroupId:
          Fn::GetAtt:
          - SourceSG
          - GroupId
        GroupId:
          Fn::GetAtt:
          - TargetSG
          - GroupId
        
  ## subnet routeTable association
    CUSTOMRTAssosiation:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        RouteTableId: !Ref CUSTOMRT
        SubnetId: !Ref PUBSUBNET

  ## Internet Gateway
    igwName:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
        - Key: name
          Value: internet
    AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref myVPC
        InternetGatewayId: !Ref igwName


   