AWSTemplateFormatVersion: 2010-09-09
###VPC###
Description:  creating vpc  
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}/VPC"

   ###puplic subnet ###    

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}/PublicSubnet"
      CidrBlock: 10.0.0.1/24
      AvailabilityZone: us-east-1a
      VpcId: !Ref VPC
      
  ###private subnet###

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}/PrivateSubnet"
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1b
      VpcId: !Ref VPC

  ###custom routetable###
  CustomRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      
  ###routetable assosioation###
  routeTableAssocName:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref CustomRouteTable

  ###InternetGateway###

  igwName:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: name
          Value: internet
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref igwName

  ###RT to IGWY ####
  RouteToIGW:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref CustomRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref igwName
  routeTableAssocName:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref CustomRouteTable

  ### Create ec2 on public subnet#####
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: virginia-kp
      ImageId: ami-0915bcb5fa77e4892
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet
  # myEC2InstanceSG:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: String security group for myEC2 instance to ssh and http port open       SecurityGroupIngress:
  #     - IPprotocol: tcp
  #     - FromPort: '80'
  #     - ToPort: '80'
  #     -
  
 
  
